
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 26 16:02:23 GMT-06:00 2018
//----------------------------------------------------

package proyectocompi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_ARRAY = 49;
  public static final int TK_INT = 14;
  public static final int TK_SEMICOLON = 31;
  public static final int TK_CASE = 7;
  public static final int TK_LPAREN = 25;
  public static final int TK_FOR = 12;
  public static final int CHAR = 50;
  public static final int TK_COMMA = 32;
  public static final int TK_RPAREN = 26;
  public static final int TK_OPREL = 37;
  public static final int INT = 47;
  public static final int TK_IF = 15;
  public static final int TK_MINUSMINUS = 39;
  public static final int COMMENT_BEGIN = 43;
  public static final int WHITESPACE = 42;
  public static final int TK_DOT = 33;
  public static final int TK_BOOLEAN = 5;
  public static final int LETRA = 45;
  public static final int ENDLINE = 41;
  public static final int TK_START = 2;
  public static final int TK_RETURN = 18;
  public static final int TK_BREAK = 6;
  public static final int TK_ASIG = 34;
  public static final int DIGIT = 46;
  public static final int TK_TRUE = 22;
  public static final int ID = 40;
  public static final int TK_NULL = 24;
  public static final int EOF = 0;
  public static final int TK_LBRACK = 29;
  public static final int error = 1;
  public static final int TK_SWITCH = 17;
  public static final int TK_WHILE = 19;
  public static final int TK_LBRACE = 27;
  public static final int TK_DEFAULT = 13;
  public static final int TK_ELSE = 11;
  public static final int TK_RBRACK = 30;
  public static final int TK_FUNC = 10;
  public static final int TK_END = 3;
  public static final int TK_OPLOG = 35;
  public static final int TK_RBRACE = 28;
  public static final int TK_FALSE = 23;
  public static final int TK_THEN = 16;
  public static final int TK_STRING = 9;
  public static final int COMMENT_END = 44;
  public static final int TK_PLUSPLUS = 38;
  public static final int TK_PRINT = 20;
  public static final int STRING = 48;
  public static final int TK_VARIABLE_TIPO = 4;
  public static final int TK_INPUT = 21;
  public static final int TK_OPMAT = 36;
  public static final int TK_CHAR = 8;
}

