
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 04 14:22:48 GMT-06:00 2018
//----------------------------------------------------

package proyectocompi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_ARRAY = 44;
  public static final int TK_INT = 14;
  public static final int TK_SEMICOLON = 29;
  public static final int TK_CASE = 7;
  public static final int TK_LPAREN = 23;
  public static final int TK_FOR = 12;
  public static final int CHAR = 45;
  public static final int TK_COMMA = 30;
  public static final int TK_RPAREN = 24;
  public static final int TK_OPREL = 35;
  public static final int INT = 42;
  public static final int TK_ELSEIF = 52;
  public static final int OPREL_NOT = 49;
  public static final int TK_IF = 15;
  public static final int MINUS = 51;
  public static final int COMMENT_BEGIN = 40;
  public static final int WHITESPACE = 39;
  public static final int TK_DOT = 31;
  public static final int AND = 47;
  public static final int TK_BOOLEAN = 5;
  public static final int TK_COMILLASIMPLE = 54;
  public static final int OR = 46;
  public static final int ENDLINE = 38;
  public static final int TK_COMILLA = 53;
  public static final int TK_START = 2;
  public static final int TK_RETURN = 18;
  public static final int TK_BREAK = 6;
  public static final int TK_ASIG = 32;
  public static final int PLUS = 50;
  public static final int ID = 37;
  public static final int TK_NULL = 22;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int TK_LBRACK = 27;
  public static final int error = 1;
  public static final int TK_SWITCH = 17;
  public static final int TK_WHILE = 19;
  public static final int TK_LBRACE = 25;
  public static final int TK_DEFAULT = 13;
  public static final int TK_ELSE = 11;
  public static final int TK_RBRACK = 28;
  public static final int TK_FUNC = 10;
  public static final int TK_END = 3;
  public static final int TK_OPLOG = 33;
  public static final int TK_RBRACE = 26;
  public static final int TK_THEN = 16;
  public static final int TK_ADDLESS = 36;
  public static final int TK_STRING = 9;
  public static final int COMMENT_END = 41;
  public static final int TK_PRINT = 20;
  public static final int STRING = 43;
  public static final int TK_VARIABLE_TIPO = 4;
  public static final int TK_INPUT = 21;
  public static final int TK_OPMAT = 34;
  public static final int TK_CHAR = 8;
}

